In [1]:
import numpy as np

In [2]:
a = np.arange(6).reshape(2,3)

In [3]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
np.argmax(a, axis=0)

array([1, 1, 1])

In [5]:
np.argmax(a, axis=1)

array([2, 2])

In [6]:
a.length

AttributeError: 'numpy.ndarray' object has no attribute 'length'

In [8]:
len(a)

2